name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on:
  release:
    types: [ published ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npm test
